databases:
  - name: hiyari_system_ver2
    databaseName: hiyari_system_ver2 db
    user: hiyari_system_ver2
    region: singapore

services:
  - type: web
    name: hiyari_system_ver2
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hiyari_system_ver2 db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
