default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  database: hiyari_system_ver2_production
  username: hiyari_system_ver2_production_user
  password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>

# PostgreSQL. Versions 9.1 and up are supported.
# default: &default
#   adapter: postgresql
#   encoding: utf8
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   database: hiyari-system_development


# test:
#   <<: *default
#   database: hiyari-system_test

# production:
#   <<: *default
#   database: hiyari-system_production
#   username: hiyari-system
#   password: <%= ENV['HIYARI-SYSTEM_DATABASE_PASSWORD'] %>
